# This is a basic workflow to help you get started with Actions
on:
  push:
jobs:
  notify:
    runs-on: alpine:3.10
    steps:
    - name: gitnotifier-test
      uses: Axel-Naumann/gitnotifier-ghaction@master
      with:
        login: test@test.test
        githubToken: ${{ secrets.GHTOKEN }}
