# This is a basic workflow to help you get started with Actions
on:
  push:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: gitnotifier-test
      uses: Axel-Naumann/gitnotifier-ghaction@master
      with:
        githubToken: ${{ secrets.GHTOKEN }}
        to: axel@cern.ch
        from: p9uriav8phvs@web.de
        smtp: smtp.web.de
        port: 587
        login: p9uriav8phvs@web.de
        password: ${{ secrets.SMTPPW }}
